services:
  frontend:
    image: node:22-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -lc "npm ci || npm i && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: dev
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

volumes:
  dbdata:
